spring:
  application:
    name: app-okta-web-api-server

logging:
  level:
    root: ${SERVER_ROOT_LOG_LEVEL:INFO}
    org.springframework: ${SERVER_SPRING_LOG_LEVEL:INFO}

server:
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT:8080}

client:
  origin-url: ${CLIENT_ORIGIN_URL}

okta:
  oauth2:
    issuer: ${SERVER_OKTA_OAUTH2_ISSUER}
    audience: ${SERVER_OKTA_OAUTH2_AUDIENCE}